### ISSUE TITLE
Support for legends

### ISSUE THREAD

**Issue by fschmenger** [wegue-oss/wegue#259]
There should be some generic support to display legend images in Wegue, so we can have useful annotations for layers.
An example screenshot taken from the geoserver docs:

![geoserver_legend_example](https://user-images.githubusercontent.com/46027124/132477074-fbc5eac7-f08f-4a55-be6d-8e326a8e4626.png)

I open this issue as a point for discussion, where those legends should be placed, what the scope of legends should be and how a structured implementation may look like.

For a first start, we could associate legends with layers and enhance the `mapLayers` app-conf definition, e.g.
```
"mapLayers": [
    {
      "lid": "my-layer",
      "legendUrl": "http://somewhere",
      ....
    }
]
```
Then we could display the legend images within the `LayerList` component.

**Comment by chrismayer** [comment]
FYI: There is a working project solution for a legend module by @JakobMiksch.
