### ISSUE TITLE
Vector layer - access members of object under properties

### ISSUE THREAD

**Issue by sgofferj** [wegue-oss/wegue#305]
After @justb4 "shamelessely plugged" wegue in a reply to a question of mine on the mapserver list, I started playing with it a little.
I'm though running into a problem trying to access an attribute which is inside of an object. Not sure if I'm just blind or if there's a bug.

I'm trying `"hoverAttribute":"announcements[0].title"` for a GeoJSON from here:
https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=false&situationType=TRAFFIC_ANNOUNCEMENT
But it doesn't work...

**Comment by justb4** [comment]
@sgofferj thanks for trying Wegue! 
Helps when sharing your JSON config file (snippet) here and let us know if e.g. geometries and other attrs rendering works and what error messages you get, e.g. in browser console.
The API call above returns GeoJSON with nested `properties`, e.g. `announcements` is array-type. This structuring may not (yet) be supported by the [OpenLayers VectorSource](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html) which is instantiated within the [Wegue Layer Factory function](https://github.com/wegue-oss/wegue/blob/master/src/factory/Layer.js#L291). Could be that only 'flat' `properties` are supported.

**Comment by sgofferj** [comment]
If I use one of the flat attributes like "SituationId", it works. Although, it also seems to only display the points, not the MultiLineStrings. Here is the config part:
```json
    {
      "type": "VECTOR",
      "lid": "Traffic",
      "name": "Traffic",
      "url": "https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=true&situationType=TRAFFIC_ANNOUNCEMENT",
      "formatConfig": {
      },
      "format": "GeoJSON",
      "visible": true,
      "selectable": true,
      "hoverable": true,
      "hoverAttribute": "announcements[0].title",
      "style": {
        "radius": 4,
        "strokeColor": "red",
        "strokeWidth": 5,
        "fillColor": "rgba(155,153,51,0.5)",
        "label": {
          "attribute": "situationId",
          "minResolution": 4.0,
          "outlineColor": "white",
          "outlineWidth": 2,
          "fillColor": "black",
          "offsetX": 0,
          "offsetY": 15,
          "align": "center"
        }
      },
      "selectStyle": {
        "radius": 10,
        "strokeColor": "gray",
        "strokeWidth": 5,
        "fillColor": "rgb(255, 255, 0, 0.2)"
      },
      "doAppendSelectStyle": true
    },
 ```
Ah, so that's all from Openlayers. I'm not familiar with that at all. I have tinkered with Leaflet before.

**Comment by fschmenger** [comment]
Hi @sgofferj,
as @justb4 pointed out, the default tooltip only supports plain attributes. You can hovever accomplish this by implementing a custom map overlay as documented in the [reusable-component section](https://github.com/wegue-oss/wegue/blob/master/docs/reusable-components.md).

**Comment by justb4** [comment]
Also the GeoJSON returned from the API has "mixed" geometries: `null`, `MultiLineString` and `Point`.
Don't know how that would be rendered by the Style. This GeoJSON validator: https://www.itb.ec.europa.eu/json/geojson/upload does not seem to be allowing `null` when validating as GeoJSON FeatureCollection.

**Comment by sgofferj** [comment]
Oh, I see. I see how easy Vue is to understand then :).
