### ISSUE TITLE
package-lock.json messed up since merge of #335

### ISSUE THREAD

**Issue by sronveaux** [wegue-oss/wegue#342]
Hi team,

While making some tests with latest commits of `Wegue` and implementing new things linked to #322 I stumbled across something messed up since merge of #335 and the commit 1cf2cfadbb2856b9d406ff8752f2be1d862831a1.

It seems like `package-lock.json` has been truncated and the last 11.000 lines are missing...

Due to the fact that it was regenerated with an older version of `NPM` (as stated in the docs) and that removing it completely and regenerating it from scratch adds some problems when running unit tests, I don't know which strategy would be the best to repair this or which one you'd prefer to follow...

Cheers,
Sébastien

**Comment by chrismayer** [comment]
Closed by #344
