### ISSUE TITLE
PDOK WMS and WFS in broken in "projected" example

### ISSUE THREAD

**Issue by chrismayer** [wegue-oss/wegue#392]
The PDOK WMS for "Natura 2000 Areas" (https://www.pdok.nl/natura2000/wms) and the PDOK WFS for "Dutch National Parks" (https://www.pdok.nl/nationaleparken/wfs) used in the "projected" example seem to be no more available. Appropriate replacements need to be set.

@justb4 Since you developed that example back in the days, are you aware of any replacements for those services/layers? TIA!

**Comment by justb4** [comment]
Very sorry, missed the notifications. Yes, there are replacements, new URL patterns for most PDOK services, and I see they have been found/fixed in #401. You can also DM me directly next time!
